/**
 * BLACKVAULT — shared domain types.
 *
 * Everything here is data. Behaviour lives in the engine modules
 * (policy/, security/, automation/, sweep/, horcrux/, chain/, swap/).
 */

/* ------------------------------------------------------------------ assets */

export type ChainId =
  | 'btc'
  | 'ltc'
  | 'xmr'
  | 'zec'
  | 'zano'
  | 'dash'
  | 'eth'
  | 'arb'
  | 'base'
  | 'sol'
  | 'usdt'
  | 'usdc'
  | 'ton'
  | 'dot'
  | 'matic';

export type AccountModel = 'utxo' | 'account' | 'shielded';

/**
 * Which real address-derivation family an asset belongs to.
 * 'sim' means the wallet derives a structurally fake but deterministic address
 * and MUST NOT be trusted for mainnet funds until a full adapter exists.
 */
export type AddressFamily = 'bitcoin' | 'ethereum' | 'monero' | 'zcash' | 'solana' | 'sim';

export interface Asset {
  id: string;
  symbol: string;
  name: string;
  chain: ChainId;
  model: AccountModel;
  decimals: number;
  /** Base price in USD, used by the simulated price feed. */
  priceUsd: number;
  /** 0 = fully transparent ledger, 100 = strong protocol-level privacy. */
  privacyScore: number;
  color: string;
  /** Address-derivation family implemented for this asset. */
  family: AddressFamily;
  /** Derivation path template (BIP44 purpose / coin type). */
  path: string;
  /** Whether the wallet can build & broadcast a sweep for this asset today. */
  sweepable: boolean;
}

/* ----------------------------------------------------------------- wallets */

export type WalletKind = 'seed' | 'passkey' | 'hardware' | 'watch' | 'horcrux';
export type Visibility = 'visible' | 'hidden' | 'decoy';
export type TierId = 0 | 1 | 2 | 3 | 4;

export interface Account {
  id: string;
  walletId: string;
  assetId: string;
  address: string;
  hdPath: string;
  /** Index inside the wallet (used for the address-rotation react). */
  index: number;
  /** Last time this account saw any movement (epoch ms). */
  lastActivity: number;
  /** Set when the account was generated by the address-rotation react. */
  rotatedFrom?: string;
}

export interface Wallet {
  id: string;
  label: string;
  kind: WalletKind;
  tier: TierId;
  visibility: Visibility;
  colorIndex: number;
  createdAt: number;
  /** Encrypted-at-rest BIP-39 mnemonic (AES-GCM envelope). Absent for watch-only. */
  mnemonicEnc?: string;
  /** WebAuthn credential id when this wallet is passkey-backed. */
  passkeyId?: string;
  /** Public fingerprint shown in Secure Send verification. */
  fingerprint: string;
  accounts: Account[];
  /** Balance snapshot cache, keyed by asset id (units, not satoshis). */
  balances: Record<string, number>;
  /** Total USD at the moment the wallet was last priced. */
  balanceUsd: number;
  /** Set when the wallet is a decoy shown under duress. */
  decoyOf?: string;
  notes?: string;
}

/* ------------------------------------------------------------------ policy */

export type RuleOutcome = 'pass' | 'challenge' | 'delay' | 'quorum' | 'deny';

export type RuleId =
  | 'maxPerTx'
  | 'dailyVelocity'
  | 'hourlyVelocity'
  | 'allowlist'
  | 'denylist'
  | 'newAddressCooldown'
  | 'timelock'
  | 'timeWindow'
  | 'shardQuorum'
  | 'passkeyThreshold'
  | 'secondDevice'
  | 'phishingShield'
  | 'secureSend'
  | 'duressTrigger'
  | 'allowanceHygiene'
  | 'privacyFloor'
  | 'autoSweep';

export interface RuleConfig {
  id: RuleId;
  enabled: boolean;
  /** Rules locked by the tier cannot be switched off (guardrail). */
  locked?: boolean;
  /** Set when edited vault-wide, so it overrides every wallet's tier default. */
  custom?: boolean;
  params: Record<string, number | string | boolean | string[]>;
}

export interface Policy {
  tier: TierId;
  rules: RuleConfig[];
  /** Per-wallet overrides keyed by wallet id. */
  overrides: Record<string, RuleConfig[]>;
  updatedAt: number;
}

export interface RuleTrace {
  ruleId: RuleId;
  label: string;
  outcome: RuleOutcome;
  detail: string;
  severity: 'info' | 'warn' | 'critical';
  /** What the user can do to satisfy the rule. */
  remediation?: string;
}

export type DecisionOutcome = 'allow' | 'challenge' | 'delay' | 'quorum' | 'deny';

export interface Decision {
  outcome: DecisionOutcome;
  /** Worst-severity reason, for one-line UI display. */
  headline: string;
  traces: RuleTrace[];
  /** Seconds to wait before broadcast (timelock / cooldown). */
  holdSeconds: number;
  /** Required Horcrux shard approvals (m of n). */
  quorum?: { m: number; n: number; purpose: string };
  /** Extra verification steps the UI must run before signing. */
  requiredSteps: ('passkey' | 'secondDevice' | 'secureSend' | 'shards' | 'duressCheck')[];
  evaluatedAt: number;
}

/* ------------------------------------------------------------- transactions */

export type TxStatus =
  | 'draft'
  | 'held'
  | 'pending'
  | 'broadcast'
  | 'confirmed'
  | 'rejected'
  | 'cancelled'
  | 'sweeping';

export type TxClass = 'send' | 'receive' | 'swap' | 'sweep' | 'shield' | 'approve';

export interface TxIntent {
  fromWalletId: string;
  assetId: string;
  amount: number;
  toAddress: string;
  /** Asset the user is swapping into, when txClass === 'swap'. */
  toAssetId?: string;
  feeRate: number;
  memo?: string;
  txClass: TxClass;
  /** True when the destination has never been seen by this vault. */
  isNewAddress?: boolean;
  /** Unlimited / large token approval simulation input. */
  approval?: { spender: string; unlimited: boolean };
}

export interface TxRecord {
  id: string;
  walletId: string;
  assetId: string;
  amount: number;
  amountUsd: number;
  toAddress: string;
  txClass: TxClass;
  status: TxStatus;
  createdAt: number;
  updatedAt: number;
  feeRate: number;
  feeUsd: number;
  confirmations: number;
  txid: string;
  /** Policy decision captured at signing time (immutable audit trail). */
  decision?: Decision;
  notes?: string;
  /** React that produced or blocked this transaction, if any. */
  reactId?: string;
}

/* -------------------------------------------------------------- automation */

export type TriggerKind =
  | 'phishing_detected'
  | 'duress_unlock'
  | 'large_outflow'
  | 'new_device'
  | 'drainer_approval'
  | 'dormant_breach'
  | 'heartbeat_missed'
  | 'key_exposure'
  | 'inbound_to_decoy'
  | 'balance_anomaly'
  | 'sweep_requested';

export type ReactAction =
  | 'freeze_outbound'
  | 'require_quorum'
  | 'notify'
  | 'self_sweep'
  | 'hide_wallets'
  | 'switch_decoy'
  | 'revoke_allowances'
  | 'rotate_addresses'
  | 'rate_limit'
  | 'wipe_session'
  | 'denylist_destination'
  | 'log_only';

export interface ReactDef {
  id: string;
  name: string;
  description: string;
  trigger: TriggerKind;
  actions: ReactAction[];
  enabled: boolean;
  /** Lowest tier whose capability set permits this react. */
  minTier: TierId;
  risk: 'defensive' | 'neutral' | 'aggressive';
  runCount: number;
  lastRun?: number;
}

export interface VaultEvent {
  id: string;
  kind: TriggerKind;
  at: number;
  severity: 'info' | 'warn' | 'critical';
  title: string;
  detail: string;
  walletId?: string;
  assetId?: string;
  amountUsd?: number;
  /** Free-form payload for react actions. */
  payload?: Record<string, unknown>;
  acknowledged?: boolean;
}

export interface ReactRun {
  id: string;
  reactId: string;
  reactName: string;
  eventId: string;
  at: number;
  actions: ReactAction[];
  outcome: 'executed' | 'blocked_by_policy' | 'skipped';
  note: string;
}

/* ---------------------------------------------------------------- horcrux */

export interface Shard {
  index: number;
  /** Hex-encoded shard payload (SSS over GF(256)). */
  hex: string;
  /** BIP39-style label for the custodian / location. */
  custodian: string;
  location: string;
  /** Short checksum shown on the printout so shards can be verified by eye. */
  checksum: string;
  /** Set once the custodian confirms possession (attestation ceremony). */
  attestedAt?: number;
}

export interface Horcrux {
  id: string;
  label: string;
  purpose: 'inheritance' | 'geo-redundancy' | 'guardian' | 'self-recovery';
  /** Threshold of shards required to reconstruct. */
  m: number;
  n: number;
  shards: Shard[];
  createdAt: number;
  /** Days of missed heartbeat before beneficiaries may claim. */
  timelockDays: number;
  lastHeartbeat: number;
  beneficiaries: { name: string; sharePct: number; contact: string }[];
  /** Owner-signed authorization reference (recovery-professional mode). */
  authorizationRef?: string;
}

export interface RecoveryClaim {
  id: string;
  createdAt: number;
  /** Where the key material came from — must be material the operator owns. */
  source: string;
  sourceKind: 'old-device' | 'paper-backup' | 'inherited' | 'shard-set' | 'hardware' | 'client-authorized';
  /** Accounts discovered by the read-only scan. */
  findings: { assetId: string; address: string; amount: number; amountUsd: number; hdPath: string }[];
  totalUsd: number;
  attestation?: {
    ownerStatement: string;
    authorizationRef: string;
    signedAt: number;
    /** WebAuthn credential or typed confirmation used to sign the attestation. */
    signedWith: string;
  };
  status: 'discovered' | 'attested' | 'sweeping' | 'complete' | 'rejected';
  destinationWalletId?: string;
  sweptTxIds?: string[];
}

/* -------------------------------------------------------------------- misc */

export interface Contact {
  id: string;
  label: string;
  address: string;
  assetId: string;
  /** Out-of-band verified fingerprint (Secure Send). */
  fingerprint: string;
  verifiedAt?: number;
  verifiedVia: 'in-person' | 'signal' | 'pgp' | 'unverified';
}

export type AuditKind =
  | 'policy'
  | 'security'
  | 'sweep'
  | 'recovery'
  | 'horcrux'
  | 'wallet'
  | 'swap'
  | 'session'
  | 'react';

export interface AuditEntry {
  id: string;
  at: number;
  kind: AuditKind;
  title: string;
  detail: string;
  severity: 'info' | 'warn' | 'critical';
}

export interface Settings {
  autoLockMinutes: number;
  hideBalances: boolean;
  /** Route reads through the configured adapter; demo mode uses the sim chain. */
  chainMode: 'sim' | 'live';
  btcEndpoint: string;
  evmEndpoint: string;
  /** Show the "duress" unlock affordance on the lock screen. */
  duressUnlockVisible: boolean;
  duressPin?: string;
  /** Simulated Tor / proxy routing toggle (UI-level statement of intent). */
  routeThroughProxy: boolean;
  fiat: 'USD' | 'EUR' | 'CHF';
  telemetry: boolean;
  /** Watchtower: generate/watch chain events and run reacts (demo: simulated feed). */
  watchtower: boolean;
  /** Signed statement the operator accepts before any recovery sweep. */
  recoveryPolicyAcceptedAt?: number;
}

export interface VaultState {
  version: number;
  createdAt: number;
  wallets: Wallet[];
  policy: Policy;
  reacts: ReactDef[];
  horcruxes: Horcrux[];
  claims: RecoveryClaim[];
  contacts: Contact[];
  txs: TxRecord[];
  events: VaultEvent[];
  reactRuns: ReactRun[];
  audit: AuditEntry[];
  settings: Settings;
  /** Duress mode hides real wallets and shows decoys. */
  duressActive: boolean;
  /** Frozen wallets cannot originate transactions until unfrozen. */
  frozenWallets: string[];
  lastSeenAt: number;
}
